const mockStockData = [
  {
    key: "AAPL",
    symbolName: "AAPL",
    name: "Apple Inc.",
    price: "150.23",
    change: "1.24",
    percent_change: "0.83",
  },
  {
    key: "MSFT",
    symbolName: "MSFT",
    name: "Microsoft Corp",
    price: "250.12",
    change: "-0.45",
    percent_change: "-0.18",
  },
  {
    key: "AMZN",
    symbolName: "AMZN",
    name: "Amazon.com Inc.",
    price: "3400.5",
    change: "12.67",
    percent_change: "0.37",
  },
  {
    key: "GOOGL",
    symbolName: "GOOGL",
    name: "Alphabet Inc.",
    price: "2800.35",
    change: "5.21",
    percent_change: "0.19",
  },
  {
    key: "META",
    symbolName: "META",
    name: "Meta Platforms Inc.",
    price: "325.16",
    change: "4.05",
    percent_change: "1.26",
  },
  {
    key: "TSLA",
    symbolName: "TSLA",
    name: "Tesla Inc.",
    price: "700.5",
    change: "-3.14",
    percent_change: "-0.45",
  },
  {
    key: "NVDA",
    symbolName: "NVDA",
    name: "NVIDIA Corporation",
    price: "220.3",
    change: "1.67",
    percent_change: "0.76",
  },
  {
    key: "NFLX",
    symbolName: "NFLX",
    name: "Netflix Inc.",
    price: "590.45",
    change: "2.34",
    percent_change: "0.4",
  },
  {
    key: "BABA",
    symbolName: "BABA",
    name: "Alibaba Group Holding Ltd.",
    price: "180.2",
    change: "3.5",
    percent_change: "1.98",
  },
  {
    key: "JPM",
    symbolName: "JPM",
    name: "JPMorgan Chase & Co.",
    price: "160.75",
    change: "-0.67",
    percent_change: "-0.42",
  },
  {
    key: "V",
    symbolName: "V",
    name: "Visa Inc.",
    price: "210.65",
    change: "1.25",
    percent_change: "0.6",
  },
  {
    key: "NKE",
    symbolName: "NKE",
    name: "Nike Inc.",
    price: "145.12",
    change: "-0.87",
    percent_change: "-0.6",
  },
  {
    key: "DIS",
    symbolName: "DIS",
    name: "The Walt Disney Company",
    price: "175.45",
    change: "2.34",
    percent_change: "1.35",
  },
  {
    key: "PYPL",
    symbolName: "PYPL",
    name: "PayPal Holdings Inc.",
    price: "240.3",
    change: "-1.12",
    percent_change: "-0.46",
  },
  {
    key: "CSCO",
    symbolName: "CSCO",
    name: "Cisco Systems Inc.",
    price: "55.12",
    change: "0.45",
    percent_change: "0.82",
  },
];

export default mockStockData;
